import chef from "../assets/chef.jpg";

export const Chefs = [
  {
    id: 0,
    name: "Evan Matthew",
    title: "Master Chef",
    desc: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divid with additional clickthroughs from Nanotechnology immersion along the information highway will close the loop on focusing solely the bottom line.",
    location: "Riverside 25, San Diego, California",
    experience: "2 years of experience",
    mail: "restaurantate@gmail.com",
    contact: "800-234-567",
    photo: chef,
  },
  {
    id: 1,
    name: "Avroko",
    title: "Master Chef",
    desc: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divid with additional clickthroughs from Nanotechnology immersion along the information highway will close the loop on focusing solely the bottom line.",
    location: "Riverside 25, San Diego, California",
    experience: "10 years of experience",
    mail: "restaurantate@gmail.com",
    contact: "800-234-567",
    photo: chef,
  },
  {
    id: 2,
    name: "Diana Clarkson",
    title: "Senior Chef",
    desc: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divid with additional clickthroughs from Nanotechnology immersion along the information highway will close the loop on focusing solely the bottom line.",
    location: "Riverside 25, San Diego, California",
    experience: "10 years of experience",
    mail: "restaurantate@gmail.com",
    contact: "800-234-567",
    photo: chef,
  },
  {
    id: 3,
    name: "Dan Rafalin",
    title: "Assistant Chef",
    desc: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divid with additional clickthroughs from Nanotechnology immersion along the information highway will close the loop on focusing solely the bottom line.",
    location: "Riverside 25, San Diego, California",
    experience: "10 years of experience",
    mail: "restaurantate@gmail.com",
    contact: "800-234-567",
    photo: chef,
  },
  {
    id: 4,
    name: "Evan Matthew",
    title: "Master Chef",
    desc: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divid with additional clickthroughs from Nanotechnology immersion along the information highway will close the loop on focusing solely the bottom line.",
    location: "Riverside 25, San Diego, California",
    experience: "10 years of experience",
    mail: "restaurantate@gmail.com",
    contact: "800-234-567",
    photo: chef,
  },
  {
    id: 5,
    name: "Diane Clarkson",
    title: "Master Chef",
    desc: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divid with additional clickthroughs from Nanotechnology immersion along the information highway will close the loop on focusing solely the bottom line.",
    location: "Riverside 25, San Diego, California",
    experience: "10 years of experience",
    mail: "restaurantate@gmail.com",
    contact: "800-234-567",
    photo: chef,
  },
];
