import foods from "../assets/foods.jpg";
import onion from "../assets/onion.jpg";

export const Food = [
  {
    id: 0,
    name: "Italian Pasta",
    desc: "Typical spaghetti is made from water, milled wheat, and flour, but authentic spaghetti is made with durum wheat semolina. Spaghetti is Italy's classic pasta that is known for its long, thin, cylindrical shape.",
    category: ["Main Courses"],
    date: "October 20, 2023",
    tags: ["Recipes", "Sweet", "Tasty"],
    photo: foods,
    Ingredients: [
      { name: "Chicken", amount: "1 Kg", id: 0, img: onion },
      { name: "Salad Leaves", amount: "250 g", id: 1, img: onion },
      { name: "Onion", amount: "500 g", id: 2, img: onion },
      { name: "Wild garlic", amount: "15x", id: 3, img: onion },
    ],
    time: "25 min",
    difficulty: "Medium",
    servings: "04",
    instructions: [
      {
        id: 0,
        name: "step 01",
        step: "Place lemon juice, lemon zest, garlic, thyme, rosemary, salt, and pepper in a large, non-reactive bowl, whisk to combine.",
      },
      {
        id: 1,
        name: "step 02",
        step: "Preheat oven to 425°F. Remove chicken from marinade and place in a single layer in a large baking dish, skin side up.",
      },
      {
        id: 2,
        name: "step 03",
        step: "Bake for 20 minutes and baste the chicken pieces generously with the reserved marinade.",
      },
      {
        id: 3,
        name: "step 04",
        step: "Until the skins are crispy brown, and the chicken is cooked through, juices running clear",
      },
      {
        id: 4,
        name: "step 05",
        step: "Pour the juices from the pan into a serving bowl. Use a tablespoon to skim the fat off the top.  Enjoy!",
      },
    ],
    calories: "230",
    saturatedFat: "0.9g",
    polyunsaturatedFat: "1.1g",
    cholesterol: "136.9 mg",
    sodium: "630.6 mg",
    protein: "54.7 g",
    potassium: "0.2 g",
  },
  {
    id: 1,
    name: "Stuffed Pasta",
    desc: "Usually served either in broth or with a pasta sauce, they originated as a traditional food in Italian cuisine. A larger version of ravioli is called ravioloni, a smaller version, ravioletti. They are typically square, though they can be circular.",
    category: ["Main Courses"],
    date: "October 20, 2023",
    tags: ["Recipes", "Sweet", "Tasty"],
    photo: foods,
    Ingredients: [
      { name: "Chicken", amount: "1 Kg", id: 0, img: onion },
      { name: "Salad Leaves", amount: "250 g", id: 1, img: onion },
      { name: "Onion", amount: "500 g", id: 2, img: onion },
      { name: "Wild garlic", amount: "15x", id: 3, img: onion },
    ],
    time: "25 min",
    difficulty: "Medium",
    servings: "04",
    instructions: [
      {
        id: 0,
        name: "step 01",
        step: "Place lemon juice, lemon zest, garlic, thyme, rosemary, salt, and pepper in a large, non-reactive bowl, whisk to combine.",
      },
      {
        id: 1,
        name: "step 02",
        step: "Preheat oven to 425°F. Remove chicken from marinade and place in a single layer in a large baking dish, skin side up.",
      },
      {
        id: 2,
        name: "step 03",
        step: "Bake for 20 minutes and baste the chicken pieces generously with the reserved marinade.",
      },
      {
        id: 3,
        name: "step 04",
        step: "Until the skins are crispy brown, and the chicken is cooked through, juices running clear",
      },
      {
        id: 4,
        name: "step 05",
        step: "Pour the juices from the pan into a serving bowl. Use a tablespoon to skim the fat off the top.  Enjoy!",
      },
    ],
    calories: "230",
    saturatedFat: "0.9g",
    polyunsaturatedFat: "1.1g",
    cholesterol: "136.9 mg",
    sodium: "630.6 mg",
    protein: "54.7 g",
    potassium: "0.2 g",
  },
  {
    id: 2,
    name: "Tubular Pasta",
    desc: "large, tubular pasta with vertical ridges that run lengthwise down the tube. It is slightly larger than penne, and is often served with meat ragu, as well as a variety of light and heavy sauces like this rigatoni in salsa rosa recipe.",
    category: ["Main Courses"],
    date: "October 20, 2023",
    tags: ["Recipes", "Sweet", "Tasty"],
    photo: foods,
    Ingredients: [
      { name: "Chicken", amount: "1 Kg", id: 0, img: onion },
      { name: "Salad Leaves", amount: "250 g", id: 1, img: onion },
      { name: "Onion", amount: "500 g", id: 2, img: onion },
      { name: "Wild garlic", amount: "15x", id: 3, img: onion },
    ],
    time: "25 min",
    difficulty: "Medium",
    servings: "04",
    instructions: [
      {
        id: 0,
        name: "step 01",
        step: "Place lemon juice, lemon zest, garlic, thyme, rosemary, salt, and pepper in a large, non-reactive bowl, whisk to combine.",
      },
      {
        id: 1,
        name: "step 02",
        step: "Preheat oven to 425°F. Remove chicken from marinade and place in a single layer in a large baking dish, skin side up.",
      },
      {
        id: 2,
        name: "step 03",
        step: "Bake for 20 minutes and baste the chicken pieces generously with the reserved marinade.",
      },
      {
        id: 3,
        name: "step 04",
        step: "Until the skins are crispy brown, and the chicken is cooked through, juices running clear",
      },
      {
        id: 4,
        name: "step 05",
        step: "Pour the juices from the pan into a serving bowl. Use a tablespoon to skim the fat off the top.  Enjoy!",
      },
    ],
    calories: "230",
    saturatedFat: "0.9g",
    polyunsaturatedFat: "1.1g",
    cholesterol: "136.9 mg",
    sodium: "630.6 mg",
    protein: "54.7 g",
    potassium: "0.2 g",
  },
  {
    id: 3,
    name: "Italian Pasta",
    desc: "Typical spaghetti is made from water, milled wheat, and flour, but authentic spaghetti is made with durum wheat semolina. Spaghetti is Italy's classic pasta that is known for its long, thin, cylindrical shape.",
    category: ["Main Courses"],
    date: "October 20, 2023",
    tags: ["Recipes", "Sweet", "Tasty"],
    photo: foods,
    Ingredients: [
      { name: "Chicken", amount: "1 Kg", id: 0, img: onion },
      { name: "Salad Leaves", amount: "250 g", id: 1, img: onion },
      { name: "Onion", amount: "500 g", id: 2, img: onion },
      { name: "Wild garlic", amount: "15x", id: 3, img: onion },
    ],
    time: "25 min",
    difficulty: "Medium",
    servings: "04",
    instructions: [
      {
        id: 0,
        name: "step 01",
        step: "Place lemon juice, lemon zest, garlic, thyme, rosemary, salt, and pepper in a large, non-reactive bowl, whisk to combine.",
      },
      {
        id: 1,
        name: "step 02",
        step: "Preheat oven to 425°F. Remove chicken from marinade and place in a single layer in a large baking dish, skin side up.",
      },
      {
        id: 2,
        name: "step 03",
        step: "Bake for 20 minutes and baste the chicken pieces generously with the reserved marinade.",
      },
      {
        id: 3,
        name: "step 04",
        step: "Until the skins are crispy brown, and the chicken is cooked through, juices running clear",
      },
      {
        id: 4,
        name: "step 05",
        step: "Pour the juices from the pan into a serving bowl. Use a tablespoon to skim the fat off the top.  Enjoy!",
      },
    ],
    calories: "230",
    saturatedFat: "0.9g",
    polyunsaturatedFat: "1.1g",
    cholesterol: "136.9 mg",
    sodium: "630.6 mg",
    protein: "54.7 g",
    potassium: "0.2 g",
  },
  {
    id: 4,
    name: "Stuffed Pasta",
    desc: "Usually served either in broth or with a pasta sauce, they originated as a traditional food in Italian cuisine. A larger version of ravioli is called ravioloni, a smaller version, ravioletti. They are typically square, though they can be circular.",
    category: ["Main Courses"],
    date: "October 20, 2023",
    tags: ["Recipes", "Sweet", "Tasty"],
    photo: foods,
    Ingredients: [
      { name: "Chicken", amount: "1 Kg", id: 0, img: onion },
      { name: "Salad Leaves", amount: "250 g", id: 1, img: onion },
      { name: "Onion", amount: "500 g", id: 2, img: onion },
      { name: "Wild garlic", amount: "15x", id: 3, img: onion },
    ],
    time: "25 min",
    difficulty: "Medium",
    servings: "04",
    instructions: [
      {
        id: 0,
        name: "step 01",
        step: "Place lemon juice, lemon zest, garlic, thyme, rosemary, salt, and pepper in a large, non-reactive bowl, whisk to combine.",
      },
      {
        id: 1,
        name: "step 02",
        step: "Preheat oven to 425°F. Remove chicken from marinade and place in a single layer in a large baking dish, skin side up.",
      },
      {
        id: 2,
        name: "step 03",
        step: "Bake for 20 minutes and baste the chicken pieces generously with the reserved marinade.",
      },
      {
        id: 3,
        name: "step 04",
        step: "Until the skins are crispy brown, and the chicken is cooked through, juices running clear",
      },
      {
        id: 4,
        name: "step 05",
        step: "Pour the juices from the pan into a serving bowl. Use a tablespoon to skim the fat off the top.  Enjoy!",
      },
    ],
    calories: "230",
    saturatedFat: "0.9g",
    polyunsaturatedFat: "1.1g",
    cholesterol: "136.9 mg",
    sodium: "630.6 mg",
    protein: "54.7 g",
    potassium: "0.2 g",
  },
  {
    id: 5,
    name: "Tubular Pasta",
    desc: "large, tubular pasta with vertical ridges that run lengthwise down the tube. It is slightly larger than penne, and is often served with meat ragu, as well as a variety of light and heavy sauces like this rigatoni in salsa rosa recipe.",
    category: ["Main Courses"],
    date: "October 20, 2023",
    tags: ["Recipes", "Sweet", "Tasty"],
    photo: foods,
    Ingredients: [
      { name: "Chicken", amount: "1 Kg", id: 0, img: onion },
      { name: "Salad Leaves", amount: "250 g", id: 1, img: onion },
      { name: "Onion", amount: "500 g", id: 2, img: onion },
      { name: "Wild garlic", amount: "15x", id: 3, img: onion },
    ],
    time: "25 min",
    difficulty: "Medium",
    servings: "04",
    instructions: [
      {
        id: 0,
        name: "step 01",
        step: "Place lemon juice, lemon zest, garlic, thyme, rosemary, salt, and pepper in a large, non-reactive bowl, whisk to combine.",
      },
      {
        id: 1,
        name: "step 02",
        step: "Preheat oven to 425°F. Remove chicken from marinade and place in a single layer in a large baking dish, skin side up.",
      },
      {
        id: 2,
        name: "step 03",
        step: "Bake for 20 minutes and baste the chicken pieces generously with the reserved marinade.",
      },
      {
        id: 3,
        name: "step 04",
        step: "Until the skins are crispy brown, and the chicken is cooked through, juices running clear",
      },
      {
        id: 4,
        name: "step 05",
        step: "Pour the juices from the pan into a serving bowl. Use a tablespoon to skim the fat off the top.  Enjoy!",
      },
    ],
    calories: "230",
    saturatedFat: "0.9g",
    polyunsaturatedFat: "1.1g",
    cholesterol: "136.9 mg",
    sodium: "630.6 mg",
    protein: "54.7 g",
    potassium: "0.2 g",
  },
];